// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProyectoFakeBook.Models;

public partial class FakeBookDBContext : DbContext
{
    public FakeBookDBContext(DbContextOptions<FakeBookDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Llafe> Llaves { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Llafe>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("llaves");

            entity.Property(e => e.Llave1).HasColumnName("llave1");
            entity.Property(e => e.Llave2).HasColumnName("llave2");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__usuarios__3213E83FB2F65D9C");

            entity.ToTable("usuarios");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apelido)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apelido");
            entity.Property(e => e.Contato)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("contato");
            entity.Property(e => e.Nome)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nome");
            entity.Property(e => e.Senha).HasColumnName("senha");
            entity.Property(e => e.Sexo).HasColumnName("sexo");
            entity.Property(e => e.Usuario1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("usuario");
        });

        OnModelCreatingPartial(modelBuilder);
    }

 

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}