// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoFakeBook.Models;

public partial class Llafe
{
    public bool Llave1 { get; set; }

    public bool Llave2 { get; set; }
}