// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoFakeBook.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Usuario1 { get; set; }

    public int? Senha { get; set; }

    public string Nome { get; set; }

    public string Apelido { get; set; }

    public string Contato { get; set; }

    public bool? Sexo { get; set; }
}